[package]
name = "taskcluster-download"
version = "54.4.2"
authors = ["Dustin J. Mitchell <dustin@mozilla.com>"]
edition = "2018"
license = "MPL-2.0"
description = "Taskcluster Download Support"
repository = "https://github.com/taskcluster/taskcluster"

[dependencies]
taskcluster = { version = "54.4.2", path = "../client" }
anyhow = "1.0"
async-trait = "0.1"
reqwest = { version = "0.11", features = ["json", "stream", "gzip", "brotli"] }
serde_json = "1.0.95"
serde = "1.0.159"
tokio = { version = "1.26", features = ["macros", "time", "fs"] }
tokio-util = { version = "0.7.7", features = ["codec", "io"] }
futures-util = "0.3"
sha2 = "0.10.2"

[dev-dependencies]
httptest = "0.15.3"
tempfile = "3"
flate2 = "1"
